### ISSUE TITLE
Add a option to set home dir via "adduser" IRC command

### ISSUE THREAD

**Issue by AayushB1** [necessary129/adminbot616#1]
Title explains it all.

**Comment by necessary129** [comment]
Specifing user dir everytime using `adduser` will be irritating for the people.
I am thinking of adding a such option to the config

**Comment by AayushB1** [comment]
Hmm, probably, then probably make a command "sethomedir username homedir"

**Comment by necessary129** [comment]
And the adduser is public, so anyone can set their homedir, which is dangerous, and you can't change someone's homedir after they have been created

**Comment by necessary129** [comment]
I will add a userhome in the config

**Comment by AayushB1** [comment]
good :)
